# Make AdminRootController the root controller for the application so people
---
Name: recipe-adminroutes
After:
  - '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    admin: false
    '': 'SilverStripe\Admin\AdminRootController'
    'a': 'SilverStripe\Admin\AdminRootController'

# Set the default area in the MOdel
SilverStripe\Admin\AdminRootController:
  url_base: 'a'
  default_panel: DogAdmin