name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        extension-csv: mbstring, xdebug, intl, fileinfo, mysql, mysqli, pdo, pdo_mysql
        
    - name: versions of everything
      shell: powershell
      run: |
        composer -V
        php -v
    
    - name: Install composer dependencies
      shell: powershell
      run: |
        composer validate
        composer require silverstripe/recipe-testing:1.x-dev silverstripe/recipe-core:4.4.x-dev silverstripe/versioned:1.4.x-dev --no-update --quiet
        
    - run: composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
      shell: powershell

    - name: Run tests
      run: vendor/bin/phpunit vendor/silverstripe/admin/tests/php
